### ISSUE TITLE
Quick formatter 

### ISSUE THREAD

**Issue by jeremyfiel** [hyperjump-io/json-schema.hyperjump.io#11]
A nice to have would be a quick formatter action. I currently copy and paste from the IDE back and forth. 

Some other little bells would be adding formatting options, spaces, indentation.. maybe incorporate prettier like config where you can define how to include line breaks for the formatting.

**Comment by jdesrosiers** [comment]
This is definitely something I run into as well and is a feature I would use myself. I'm often dropping in schemas from StackOverlow or Slack questions and they often need their indentation normalized to make them easier to work with. I definitely wouldn't do something as heavy as incorporating prettier, but something simple would make sense. The easiest thing to do would be to just format with `JSON.stringify(schema, null, "  ")`, but that doesn't always match my preferred style well. I tend to collapse small objects/schemas such as `{ "$ref": "..." }` to one line.

For me personally, what I generally want is just indentation normalization. Would that be sufficient for your needs, or are there other issues you run into?

**Comment by jeremyfiel** [comment]
I think starting with indentation and normalizing the structure would be sufficient for now.  Perks can come later like customized indents or formatting prefs if you ever feel so inclined on a late Tuesday night with nothing better to do   😜

**Comment by jeremyfiel** [comment]
Also, you mentioned collapsing, not sure if that's something to easily incorporate too.  Would definitely be a welcome addition along with line numbers

**Comment by jdesrosiers** [comment]
I added a format button that uses the default formatting you get with `JSON.stringify`. That's less useful for me personally than a feature that just fixes indentation, but this was a lot easier to do and it's better than nothing.

**Comment by jeremyfiel** [comment]
so this has an interesting, unexpected (kind of) behavior.. 

### take this example, 

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "singleton": {
      "type": "string"
    },
    "singleton": {
      "not": {
        "type": [
          "boolean",
          "object",
          "array",
          "integer",
          "number",
          "null"
        ]
      }
    }
  },
  "required": [
    "singleton"
  ],
  "unevaluatedProperties": false
}
```

### It turns into this... 

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "singleton": {
      "not": {
        "type": [
          "boolean",
          "object",
          "array",
          "integer",
          "number",
          "null"
        ]
      }
    }
  },
  "required": [
    "singleton"
  ],
  "unevaluatedProperties": false
}
```

if you use the formatter, it merges the `singleton` keyword and removes the `type` declaration completely.  AND  depending on the order of the JSON properties, it seems to take the last one, which completely removes constraints from the first instance of the next example. 

### This... 
```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "singleton": {
      "not": {
        "type": [
          "boolean",
          "object",
          "array",
          "integer",
          "number",
          "null"
        ]
      }
    },
    "singleton": {
      "type": "string"
    }
  },
  "required": [
    "singleton"
  ],
  "unevaluatedProperties": false
}
```

### turns into this....
```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "singleton": {
      "type": "string"
    }
  },
  "required": [
    "singleton"
  ],
  "unevaluatedProperties": false
}
```

**Comment by jdesrosiers** [comment]
I was working on something else and came across a library I could use for formatting JSON with a few options. So, I added a settings button in the top right corner you can use to configure a few formatting options.
